### ISSUE TITLE
help

### ISSUE THREAD

**Issue by shoelyshtya** [dibaliqaja/pesantren-cms#31]
file databanenya dimana ya kak
apa ini uah ada notif whatsapp kak

**Comment by dibaliqaja** [comment]
Halo @shoelyshtya 
Untuk _table database_-nya nanti akan di-_generate_ langsung menggunakan `php artisan migrate`. Jadi tidak perlu _import_ manual terlebih dahulu.
Dan untuk aplikasi ini belum ada notifikasi Whatsapp
